PLAT-2422 Add integration test with quickstart
opentdf/client-java pull request #6
Opened 2023-04-24 03:34 UTC by elizabethhealy

2023-04-24 13:59 UTC, mustyantsev commented on wait-and-test.sh
> +cd "${MAKEFILE_LOCTION}"
```suggestion
cd "${MAKEFILE_LOCATION}"?
```

2023-04-24 14:05 UTC, dmihalcik-virtru requested changes

2023-04-24 14:05 UTC, dmihalcik-virtru commented on .github/workflows/build.yml
> +          retention-days: ${{ fromJSON('{"false":90,"true":3}')[github.event_name == 'pull_request'] }}
Does GitHub expression language not have a ternary?

https://docs.github.com/en/actions/learn-github-actions/expressions#operators

What I guess not? Should `(a && b) || c` work? I guess in this case

```suggestion
          retention-days: ${{ github.event_name == 'pull_request' && 3 || 90 }}
```

seems clearer to me but IDK whatever if it works it works both are a little obscure

2023-04-24 14:05 UTC, dmihalcik-virtru commented on .github/workflows/build.yml
> +          distribution: 'temurin' # See 'Supported distributions' for available options
```suggestion
          # See https://github.com/actions/setup-java#supported-distributions for list
          distribution: 'temurin'
```

2023-04-24 14:05 UTC, dmihalcik-virtru commented on examples/sample.java
>        } catch (Exception e) {
I'd suggest only catching RuntimeExceptions instead. Tf this code is intended as a reference it might be nice to have a list of checked exceptions here as well.

2023-04-24 14:05 UTC, dmihalcik-virtru commented on wait-and-test.sh
> +_wait-for
Can you run this through shfmt?

2023-05-04 20:07 UTC, dmihalcik-virtru approved these changes

2023-05-04 20:39 UTC, merged